models:
  - name: int_sales_enriched
    columns:
      - name: order_item_id
        description: "Primary key for this table."
        tests:
          - not_null

  - name: int_staff_hierarchy
    columns:
      - name: staff_id
        description: "Primary key for this table."
        tests:
          - not_null

  - name: int_store_stock
    columns:
      - name: store_id
        description: "Primary key for this table."
        tests:
          - not_null            
